export class constantsX {
  public static newAccountName: any = {
    'Select Account..': -1,
    Transaction: 0,
    Cash: 1,
    'Accounts receivable': 2,
    'Allowance for Uncollectables or Bad debt': 3,
    'Unbilled Revenue': 4,
    Investments: 5,
    PPE: 6,
    'Accm. Depn': 7,
    Goodwill: 8,
    Land: 9,
    'Accounts payable': 10,
    'Unearned Revenue': 11,
    'Notes payable': 12,
    'Interest payable': 13,
    'Dividend payables': 14,
    'Bonds payable': 15,
    'Bond discount': 16,
    'Bond premium': 17,
    'Common stock': 18,
    'Retained Earnings': 19,
    'Treasury stock': 20,
    'Addnl. Paid in Capital': 21,
    'Unrealized Gain': 22,
    'Unrealized Loss': 23,
    Revenue: 24,
    'Investment Income': 25,
    'Profit on retirement of bonds': 26,
    'Realized gain': 27,
    Gain: 28,
    'Insurance Expense': 29,
    'Bad debt Expense': 30,
    'Depreciation Expense': 31,
    'Goodwill Amortization Expense': 32,
    'Interest expense': 33,
    Loss: 34,
    'Realized loss': 35,
    'Dividend/Investment income': 36,
  };

  public static accountName: any = {
    'Select Account..': -1,
    Transaction: 0,
    Cash: 1,
    'Accounts Receivable': 2,
    'Allowance for Bad Debts': 3,
    Inventory: 4,
    'Pre Paid Asset': 5,
    'Intangible Assets': 6,
    'Other Assets': 7,
    Investments: 8,
    Goodwill: 9,
    PPE: 10,
    'Accumulated Depreciation': 11,
    'Accounts payable': 12,
    'Wages Payable': 13,
    'Interest Payable': 14,
    'Notes Payable': 15,
    'Deferred Revenue': 16,
    'Bank Loan': 17,
    'Bonds payable': 18,
    'Other Liabilities': 19,
    'Dividends payable': 20,
    'Common stock': 21,
    'Addnl. Paid in Capital': 22,
    'Treasury stock': 23,
    'Retained Earnings': 24,
    Revenue: 25,
    'Investment Income': 26,
    'Profit on Retirement of Bonds': 27,
    'Dividend income': 28,
    CoGS: 29,
    'Rent Expenses': 30,
    'Depreciation Expenses': 31,
    'Wage Expenses': 32,
    'Interest Expenses': 33,
    'Insurance Expenses': 34,
    'Bad debt Expenses': 35,
    'Selling & General Expenses': 36,
    'Other Expenses': 37,
    'Goodwill Amortization Expense': 38,
  };
}
