export class constantsX {
  // public static accountName: any = {
  //   'Select Account..': -1,
  //   Transaction: 0,
  //   'Accm. Depn': 1,
  //   'Accounts payable': 2,
  //   'Accounts receivable': 3,
  //   'Addnl. Paid in Capital': 4,
  //   'Allowance for Uncollectables or Bad debt': 5,
  //   'Bad debt Expense': 6,
  //   'Bond discount': 7,
  //   'Bond premium': 8,
  //   'Bonds payable': 9,
  //   Cash: 10,
  //   'Common stock': 11,
  //   'Depreciation Expense': 12,
  //   'Dividend/Investment income': 13,
  //   Goodwill: 14,
  //   'Goodwill Amortization Expense': 15,
  //   'Interest expense': 16,
  //   Investments: 17,
  //   'Investment Income': 18,
  //   Land: 19,
  //   Loss: 20,
  //   PPE: 21,
  //   'Profit on retirement of bonds': 22,
  //   'Realized gain': 23,
  //   'Retained Earnings': 24,
  //   Revenue: 25,
  //   'Treasury stock': 26,
  //   'Unbilled Revenue': 27,
  //   'Unearned Revenue': 28,
  //   'Unrealized Gain': 29,
  //   'Unrealized Loss': 30,
  //   'Realized loss': 31,
  //   Gain: 32,
  //   'Dividend payables': 33,
  //   'Insurance Expense': 34,
  //   'Notes payable': 35,
  //   'Interest payable': 36,
  // };

  public static accountName: any = {
    'Select Account..': -1,
    Transaction: 0,
    Cash: 1,
    'Accounts receivable': 2,
    'Allowance for Uncollectables or Bad debt': 3,
    'Unbilled Revenue': 4,
    Investments: 5,
    PPE: 6,
    'Accm. Depn': 7,
    Goodwill: 8,
    Land: 9,
    'Accounts payable': 10,
    'Unearned Revenue': 11,
    'Notes payable': 12,
    'Interest payable': 13,
    'Dividend payables': 14,
    'Bonds payable': 15,
    'Bond discount': 16,
    'Bond premium': 17,
    'Common stock': 18,
    'Addnl. Paid in Capital': 19,
    'Treasury stock': 20,
    'Retained Earnings': 21,
    'Unrealized Gain': 22,
    'Unrealized Loss': 23,
    Revenue: 24,
    'Investment Income': 25,
    'Profit on retirement of bonds': 26,
    'Realized gain': 27,
    Gain: 28,
    'Insurance Expense': 29,
    'Bad debt Expense': 30,
    'Depreciation Expense': 31,
    'Goodwill Amortization Expense': 32,
    'Interest expense': 33,
    Loss: 34,
    'Realized loss': 35,
    'Dividend/Investment income': 36,
  };
}
