export class constantsX {
  public static accountName: any = {
    'Select Account..': -1,
    Transaction: 0,
    Cash: 1,
    'Accounts receivable': 2,
    'Allowance for Uncollectables or Bad debt': 3,
    'Unbilled Revenue': 4,
    Investments: 5,
    PPE: 6,
    'Accm. Depn': 7,
    Goodwill: 8,
    Land: 9,
    'Accounts payable': 10,
    'Unearned Revenue': 11,
    'Notes payable': 12,
    'Interest payable': 13,
    'Dividend payables': 14,
    'Bonds payable': 15,
    'Bond discount': 16,
    'Bond premium': 17,
    'Common stock': 18,
    'Addnl. Paid in Capital': 19,
    'Treasury stock': 20,
    'Retained Earnings': 21,
    'Unrealized Gain': 22,
    'Unrealized Loss': 23,
    Revenue: 24,
    'Investment Income': 25,
    'Profit on retirement of bonds': 26,
    'Realized gain': 27,
    Gain: 28,
    'Insurance Expense': 29,
    'Bad debt Expense': 30,
    'Depreciation Expense': 31,
    'Goodwill Amortization Expense': 32,
    'Interest expense': 33,
    Loss: 34,
    'Realized loss': 35,
    'Dividend/Investment income': 36,
  };

  public static contraAccounts: any  = {
    PPE : 'Accm. Depn',
    'Accounts receivable' : 'Allowance for Uncollectables or Bad debt',
    'Bonds payable' : 'Bond discount',
    'Common stock' : 'Treasury stock'
  }
}
